@startuml
title Сервис распространения настроек
participant grpc as "Интерфейс"
box properties-server
    participant service as "Сервис"
    participant cache as "Кеш"
    database pg as "СУБД"
    participant provider as "Провайдер"
end box
participant user as "Потребитель"

== Загрузка сервиса ==

service -> service: Инициализация контекста
service -> pg: Запрос всех настроек для прогрева кеша
alt #LightPink база не доступна
  service <--x pg: не запуск сервиса
else #LightGreen доступна
  service <-- pg: множество настроек
  service -> cache: сохранение настроек в кеше
end
  service -> service: продолжение загрузки

==  Получение настроек через  ""GRPC"" ==

grpc -> service: <b>GRPC</b> ""/properties/GetScopedValue""
activate service
service -> cache: Запрос настроек из кеша
alt #LightGreen есть данные
  cache --> service: данные
  service --> grpc: Возвращение настройки
else нет данных
  cache --> service: нет данные
  service -> pg: Запрос настроек
  alt база жива
    pg --> service: данные
    service -> cache: обновляем кеш
    service --> grpc: запрошенные настройки
  else #LightPink база не жива
    pg x--> service
    service --> grpc: сервис не доступен
  else #LightYellow нет настройки
    pg --> service: данные
    service --> grpc: нет такой настройки
  end
end
deactivate service

==  Изменение настроек через  ""GRPC"" ==
grpc -> service: <b>GRPC</b> ""/properties/UpdScopedValue""\n<b>GRPC</b> ""/properties/DelScopedValue""
activate service
service -> service: проверка прав на изменение, <b>JWT</b>
alt #LightPink нет прав
  service --> grpc: нет прав + 403 код
else #LightGreen есть права
  service -> pg: Запрос на обновление
  alt #LightYellow не удалось выполнить
    pg x--> service: ошибка или нет доступа
    service --> grpc: ошибка + код
  else #LightGreen  выполнили
    pg --> service: настройка изменена
    service -> cache: обновляем кеш
    service -> provider: оповещение об изменении
    service --> grpc: настройка изменена
  end
end
deactivate service

loop оповещение потребителя
  provider -> user: настройка изменена
end

@enduml
