CREATE DATABASE cdc ENCODING 'UTF-8';
\c cdc
CREATE SCHEMA properties;
SET search_path='properties';
CREATE TABLE site(
    id       SERIAL PRIMARY KEY,
    key      VARCHAR NOT NULL,
    value    VARCHAR NOT NULL,
    expires  TIMESTAMP,
    refresh  INTEGER NOT NULL DEFAULT 3600,
    created  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(key)
);
CREATE TABLE mobile(
    id       SERIAL PRIMARY KEY,
    key      VARCHAR NOT NULL,
    value    VARCHAR NOT NULL,
    expires  TIMESTAMP,
    refresh  INTEGER NOT NULL DEFAULT 3600,
    created  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(key)
);
