spring:
  application:
    name: named-count
  r2dbc:
    pool:
      enabled: true
      initial-size: 10
      max-size: 10
    properties:
      schema: properties
    url: r2dbc:postgresql://${POSTGRES_HOSTNAME:postgres:5432}/named_count
    username: postgres
    password: postgres
  data:
    redis:
      host: ${REDIS_HOSTNAME:redis}
logging:
  level:
    root: INFO
  charset:
    console: UTF-8

app:
  properties:
    cached: true
    cached-expires: 60s
