spring:
  application:
    name: named-count
    admin:
      enabled: true
  r2dbc:
    pool:
      enabled: true
      initial-size: 10
      max-size: 10
    properties:
      schema: named
    url: r2dbc:postgresql://${POSTGRES_HOSTNAME:postgres:5432}/named_count
    username: postgres
    password: postgres
  data:
    redis:
      host: ${REDIS_HOSTNAME:redis}
      port: ${REDIS_PORT:6379}
  jmx:
    enabled: true

logging:
  level:
    root: INFO
  charset:
    console: UTF-8

app:
  port: 30323
  stream:
    strategy: string
